export const ADD_NEW_POST = "ADD_NEW_POST";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const INPUT_CHANGE_HANDLER = "INPUT_CHANGE_HANDLER";
export const SET_USERS = "SET_USERS";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_TOTAL_USERS_COUNT = "SET_TOTAL_USERS_COUNT";
export const CHANGE_LOAD = "CHANGE_LOAD";
export const SET_USER_PROFILE = "SET_USER_PROFILE";
export const SET_USER_DATA = "SET_USER_DATA";
export const FOLLOW_USER = "FOLLOW_USER";
export const UNFOLLOW_USER = "UNFOLLOW_USER";
export const TOGGLEFOLLOWING = "TOGGLEFOLLOWING";
export const SET_STATUS = "SET_STATUS";
export const UPDATE_STATUS = "UPDATE_STATUS";
export const LOGIN = "LOGIN";


